### ISSUE TITLE
Needs to support 2.7, 3.5, 3.6 & 3.7 on pypi.org

### ISSUE THREAD

**Issue by dynata-bradley** [dynata/python-demandapi-client#36]
<img width="305" alt="Screen Shot 2020-01-14 at 12 29 57 PM" src="https://user-images.githubusercontent.com/51792608/72371311-bcacf780-36c9-11ea-84cf-2732ceb90adb.png">

**Comment by DynataRidley** [comment]
Resolved by #37.
