### ISSUE TITLE
refactor pause/close/launch line items

### ISSUE THREAD

**Issue by wogsland** [dynata/python-demandapi-client#41]
<img width="864" alt="Screen Shot 2020-01-20 at 9 59 56 AM" src="https://user-images.githubusercontent.com/3073735/72740671-c58b4680-3b6b-11ea-80e9-acd442bc574f.png">

**Comment by DynataRidley** [comment]
See https://github.com/dynata/python-demandapi-client/issues/44#issuecomment-577418539
