### ISSUE TITLE
Split up DemandAPIClient class

### ISSUE THREAD

**Issue by wogsland** [dynata/python-demandapi-client#42]
<img width="895" alt="Screen Shot 2020-01-20 at 10 02 44 AM" src="https://user-images.githubusercontent.com/3073735/72740823-13a04a00-3b6c-11ea-86db-6a79a3b46d02.png">

**Comment by DynataRidley** [comment]
:-1: This is a necessary evil. See https://github.com/sns-sdks/python-facebook/blob/master/pyfacebook/api/facebook.py, https://github.com/bear/python-twitter/blob/master/twitter/api.py, https://github.com/twilio/twilio-python/blob/master/twilio/rest/api/v2010/account/__init__.py, all these API SDKs all have a bunch of functions for each endpoint they support.

**Comment by wogsland** [comment]
The Facebook file you reference only has 15 functions in the class.

The Twilio library has a ton of small classes doing most of the things. The file you reference for example has 6 classes in it, none of which exceed 20 functions.

Okay the Twitter one has over 100, but this certainly doesn't seem to be the rule from the examples you provided.
