### ISSUE TITLE
Refactor line item gets

### ISSUE THREAD

**Issue by wogsland** [dynata/python-demandapi-client#43]
<img width="668" alt="Screen Shot 2020-01-20 at 10 04 29 AM" src="https://user-images.githubusercontent.com/3073735/72740951-506c4100-3b6c-11ea-99c5-5d8405c420c5.png">

**Comment by DynataRidley** [comment]
See https://github.com/dynata/python-demandapi-client/issues/44#issuecomment-577418539. Unless you have an idea about how this should be refactored then I think this is probably as good as we need to get.
