### ISSUE TITLE
Refactor get functions

### ISSUE THREAD

**Issue by wogsland** [dynata/python-demandapi-client#44]
<img width="860" alt="Screen Shot 2020-01-20 at 10 06 36 AM" src="https://user-images.githubusercontent.com/3073735/72741127-9de8ae00-3b6c-11ea-89a9-f416114fdae7.png">

<img width="840" alt="Screen Shot 2020-01-20 at 10 06 44 AM" src="https://user-images.githubusercontent.com/3073735/72741144-a640e900-3b6c-11ea-8568-2c2ef5e0c9e1.png">

**Comment by DynataRidley** [comment]
I mean, moving the validation stuff to its own module _is_ the refactor. I don't think there's anything else to do here.
