### ISSUE TITLE
Refactor reading in environment variables

### ISSUE THREAD

**Issue by wogsland** [dynata/python-demandapi-client#46]
<img width="866" alt="Screen Shot 2020-01-20 at 10 11 42 AM" src="https://user-images.githubusercontent.com/3073735/72741467-531b6600-3b6d-11ea-85c7-063d934251a4.png">

**Comment by DynataRidley** [comment]
See https://github.com/dynata/python-demandapi-client/pull/47#issuecomment-577417806
